### ISSUE TITLE
Solo Project: Milestone 2

### ISSUE THREAD

**Issue by bChakrabarty** [data301-2020-winter1/course-project-solo_204#2]
- [x] Should add more comments to explain what each chunk of code is doing.

- [x] Make the graphs more readable.

- [x] Add more graphs
